### ISSUE TITLE
Upgrade to metrics 3.1.0

### ISSUE THREAD

**Issue by dclements** [ReadyTalk/metrics-statsd#16]
Metrics has changed packages to io.dropwizard.metrics. We should update and create a new version to take advantage of changes in the new line.

**Comment by tulinski** [comment]
Why the pull-request with metrics-core update hasn't been merged yet? Are you planning to switch to the newest io.dropwizard version?

**Comment by dclements** [comment]
Most of the people who were maintaining this project are no longer at RT (or won't be shortly) and thus no longer have permissions to merge it (myself included). I suspect the rest of the company has been busy with the [acquisition](http://www.denverpost.com/2017/01/13/readytalk-acquired-by-pgi/), so I am not sure when/if this will be prioritized. 

FWIW the change LGTM.
