### ISSUE TITLE
Promote to jcenter

### ISSUE THREAD

**Issue by daviddenton** [ReadyTalk/metrics-statsd#17]
Would it be possible to get the bintray project added to jcenter or <shudder/> sonatype/maven central? I suspect that jcenter will be less depression-inducing... :)

**Comment by watsoncj** [comment]
Seems like the right direction to go.

Bintray needs a source jar before it will allow us to add the project to jcenter.

**Comment by daviddenton** [comment]
There's also this guide to setting up the maven Central synchronisation. Having done it myself recently, I can confirm that once you get over the manual Jira hump (really!), it's not too bad. As such, the second project you want to add to MC is much quicker than the first...

http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/

**Comment by mkeesey** [comment]
I'll see if I can get something set up in the next few days.

**Comment by cooniur** [comment]
+1 for the project going to jcenter.

**Comment by watsoncj** [comment]
The repository has been linked to JCenter. However, for some reason we still aren't getting artifacts into the JCenter CDN.

**Comment by daviddenton** [comment]
Version 4.1.2 seems to now be in JCenter & the ReadyTalk bintray repos, but v4.1.0 has now disappeared completely. 

Was this just an artifact of this particular change or was it intentional, as disappearing artifacts are obviously a "Really (Really) Bad Thing"?

**Comment by watsoncj** [comment]
Thanks for pointing this out. It most certainly was not intentional. I suspect this was a side-effect of repurposing the existing jCenter repo of the same name to readytalk/maven/metrics-statsd.

I've republished the missing 4.1.0 version. Apologies for the inconvenience.

Are you actually able to resolve the 4.1.2 artifact from jCenter?

```
apply plugin: 'java'

repositories {
  jcenter()
}

dependencies {
  compile 'com.readytalk:metrics3-statsd:4.1.2'
}

task wrapper(type: Wrapper) {
  gradleVersion = '2.3'
}
```

```
* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find com.readytalk:metrics-statsd-common:4.1.2.
  Searched in the following locations:
      https://jcenter.bintray.com/com/readytalk/metrics-statsd-common/4.1.2/metrics-statsd-common-4.1.2.pom
      https://jcenter.bintray.com/com/readytalk/metrics-statsd-common/4.1.2/metrics-statsd-common-4.1.2.jar
  Required by:
      :metrics-statsd-test:unspecified > com.readytalk:metrics3-statsd:4.1.2
```

**Comment by daviddenton** [comment]
Thanks for fixing quickly - it was causing a real headache for us yesterday!

We get sporadic failures trying to resolve the 4.1.2 artifacts - I suspect that it just hasn't been correctly distributed to all of the JCenter nodes which causes the intermittency. 

Can I suggest pushing out a 4.1.3 to JCenter to see if that resolves the problem?

**Comment by watsoncj** [comment]
I totally understand what a pain it can be. Sorry If I caused it.

I received this message from Bintray this morning:

> Hi Casey, First, we wanted to update you that we have fixed the issue (by re-linking the package to JCenter). In addition, the original inclusion request was for "com/readytalk/metrics3-statsd" this resulted in an inclusion of all the files under this path. However, the files you requested were uploaded to a different path "com/readytalk/metrics-statsd-common" and this is why the files were unavailable. We have included the path "com/readytalk" which means that all of the files under this path are now available. Best Regards, Bintray Team

I've also confirmed that I can resolve `com.readytalk:metrics3-statsd:4.1.2` using only the jCenter repository.

Example `build.gradle`:

```
apply plugin: 'java'

repositories {
  jcenter()
}

dependencies {
  compile 'com.readytalk:metrics3-statsd:4.1.2'
}
```

We'll probably want to update the readme as well.
