### ISSUE TITLE
everything in statsd become gauges

### ISSUE THREAD

**Issue by tailorcai** [ReadyTalk/metrics-statsd#21]
gauge will overwrite old values in statsd which make distributed counters impossible

**Comment by dclements** [comment]
Please see Issue #20 and Issue #15 and my comment on [organicveggie#4](https://github.com/organicveggie/metrics-statsd/pull/4#issuecomment-29748201). 

Long story less long: If you want the statsd distributed counters, the dropwizard/codahale metrics library is not a usable solution to that problem, you'll need to send your counter inc/dec directly to statsd.
