### ISSUE TITLE
Allow to send non-aggregates values

### ISSUE THREAD

**Issue by augi** [ReadyTalk/metrics-statsd#32]
The default settings of [statsite](https://github.com/statsite/statsite#configuration-options) is that it computes various percentiles, max, min etc.

The problem is that `metrics-statsd` sends also various percentiles to StatsD/statsite and so you end with _percentiles of percentiles_ in Graphite.

It would be nice to be able to configure the reporter to send _raw_ data instead of aggregated.

I could prepare the pull request if you would mind accepting it.

Btw. our use-case is that we sends application metrics from more instances of the application. These instances are running in a cloud so we don't have fixed identifiers of the running instances. We also don't want to add a random hash to metric name because it would cause problems in Whisper (DB of Graphite) - it doesn't like higher number of files.

**Comment by PetroccoCo** [comment]
Hey @augi 
This project is on the back burner for us right now, but if you open a pull request we will certainly do our best to get it reviewed and merged.
Thanks!

**Comment by augi** [comment]
Btw. my original statement wasn't true - percentile of percentile is not computed because all the values are reported as gauge.
